config/routes.rb
Rails.application.routes.draw do
  get 'recipes/display'
  get 'recipes/details'
  get 'displays/display'
  #get 'recipes/search'
  resources :categories
  resources :favorites
  resources :shoppings
  resources :blocks
  get 'home/top'
  root to:'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/profile', to: 'users#show'
  delete '/unsubscribe', to: 'users#destroy'
  
  #get '/users/:id', to: 'users#show', as: 'profile'
  #delete '/users/:id', to: 'users#destroy', as: 'unsubscribe'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/recipes_search', to: 'recipes#search'
  post '/recipes_search', to: 'recipes#search'

  post 'addfood', to: 'shoppings#addfood'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :recipe, optional: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[ show edit update destroy ]

  # GET /favorites or /favorites.json
  def index
    @favorites = Favorite.where(user_id: current_user)
  end

  # GET /favorites/1 or /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites or /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.user_id = current_user.id

    if @favorite.save
      redirect_to recipes_search_path(anchor:favorite_params["recipe_id"],search:true)
    else
      redirect_to recipes_sarch_path, notice: "Favorite was succesfully failed."
    end
      #   respond_to do |format|
#     if @favorite.save
#       format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully created." }
#       format.json { render :show, status: :created, location: @favorite }
#     else
#       format.html { render :new, status: :unprocessable_entity }
#       format.json { render json: @favorite.errors, status: :unprocessable_entity }
#     end
#   end
  end

  # PATCH/PUT /favorites/1 or /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully updated." }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1 or /favorites/1.json
  def destroy
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Favorite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :favorite, :recipe_id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <div class="field">
    <%= form.label :favorite %>
    <%= form.text_field :favorite %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<div class="blocktitle">
  <h1>お気に入り </h1>
</div>

<%#ホームアイコン%>
<%= link_to home_top_path do %>
  <%= image_tag "/images/home.png",{class: "homeicon"} %>
<% end %>
<br>
<br>

<style>
.example{
    display: inline-block;
}
.example img{
    display: block;
}
</style>

<table>
  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
          <td><%= link_to favorite.recipe.recipeTitle, recipes_details_path(id: favorite.recipe_id)%></td>
          <td><%= link_to recipes_details_path(id: favorite.recipe_id) do %>
                    <div class="image">
                        <%= image_tag favorite.recipe.foodImageUrl %>
                    </div>
                <% end %>
          </td>
          <td><%= link_to '削除', favorite, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @favorite.favorite %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>