config/routes.rb
Rails.application.routes.draw do
  get 'recipes/display'
  get 'recipes/details'
  get 'displays/display'
  #get 'recipes/search'
  resources :categories
  resources :favorites
  resources :shoppings
  resources :blocks
  get 'home/top'
  root to:'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/profile', to: 'users#show'
  delete '/unsubscribe', to: 'users#destroy'
  
  #get '/users/:id', to: 'users#show', as: 'profile'
  #delete '/users/:id', to: 'users#destroy', as: 'unsubscribe'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/recipes_search', to: 'recipes#search'
  post '/recipes_search', to: 'recipes#search'

  post 'addfood', to: 'shoppings#addfood'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<h1 class="title">Let's Help Cook</h1>

<div class="row">
    <div class="col-12 col-md-6">
      <%= link_to recipes_search_path, {class: "ss"} do %>
      <div class="card">
        <%= image_tag "/images/search.png",{class: "card-image-top"} %>
        <div class="card-body">
          <h3 class="card-title">レシピ検索</h3>
          <p class="card-text">レシピの検索ができます。</p>
        </div>
      </div>
      <%end%>
    </div>
    
    <div class="col-12 col-md-6">
      <%= link_to favorites_path, {class: "ss"} do %>
      <div class="card">
        <%= image_tag "/images/favo.png",{class: "card-image-top"}%>
        <div class="card-body">
          <h3 class="card-title">お気に入り</h3>
          <p class="card-text">お気に入りに登録したレシピが閲覧できます。</p>
        </div>
      </div>
      <%end%>
    </div>
</div>



<div class="row">
   <div class="col-12 col-md-6">
      <%= link_to blocks_path, {class: "ss"} do %>
      <div class="card">
        <%= image_tag "/images/batsu_l.png",{class: "card-image-top"} %>
        <div class="card-body">
          <h3 class="card-title">ブロック</h3>
          <p class="card-text">アレルギーなどの食材をブロックできます。</p>
        </div>
      </div>
      <%end%>
    </div>

    <div class="col-12 col-md-6">
      <%= link_to shoppings_path, {class: "ss"} do %>
      <div class="card">
        <%= image_tag "/images/shopping3_l.png",{class: "card-image-top"} %>
        <div class="card-body">
          <h3 class="card-title">買い物リスト</h3>
          <p class="card-text">購入予定の食材などを追加・閲覧できます。</p>
        </div>
      </div>
      <%end%>
    </div>
</div>