config/routes.rb
Rails.application.routes.draw do
  get 'recipes/display'
  get 'recipes/details'
  get 'displays/display'
  #get 'recipes/search'
  resources :categories
  resources :favorites
  resources :shoppings
  resources :blocks
  get 'home/top'
  root to:'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/profile', to: 'users#show'
  delete '/unsubscribe', to: 'users#destroy'
  
  #get '/users/:id', to: 'users#show', as: 'profile'
  #delete '/users/:id', to: 'users#destroy', as: 'unsubscribe'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/recipes_search', to: 'recipes#search'
  post '/recipes_search', to: 'recipes#search'

  post 'addfood', to: 'shoppings#addfood'
end

app/models/block.rb
class Block < ApplicationRecord
    belongs_to :user, optional: true
    validates :block, presence: true
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: %i[ show edit update destroy ]

  # GET /blocks or /blocks.json
  def index
    @blocks = Block.where(user_id: current_user.id)
  end

  # GET /blocks/1 or /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks or /blocks.json
  def create
    @block = Block.new(block_params)
    @block.user_id = current_user.id

    respond_to do |format|
      if @block.save
        format.html { redirect_to block_url(@block), notice: "Block was successfully created." }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1 or /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to block_url(@block), notice: "Block was successfully updated." }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1 or /blocks/1.json
  def destroy
    @block.destroy

    respond_to do |format|
      format.html { redirect_to blocks_url, notice: "Block was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def block_params
      params.require(:block).permit(:block, :user_id)
    end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<%= form_with(model: block) do |form| %>
  <% if block.errors.any? %><br>
  <div id="error_explanation">
    <ul class="era">
        <% block.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
     </ul>
   </div>
  <% end %>


  <div class="field">
    <%= form.label :block %>
    <%= form.text_field :block %>
  </div>

  <!--div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div-->

  <div class="actionsb">
    <%= form.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<div class="blocktitle">
  <h1>編集</h1>
  <br>
</div>

  <%= render 'form', block: @block %>

<div class="modoru">
  <%= link_to '詳細', @block %> |
  <%= link_to '戻る', blocks_path %>
</div>

app/views/blocks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="blocktitle">
<h1>ブロック</h1>
</div>

<%#ホームアイコン%>
<%= link_to home_top_path do %>
  <%= image_tag "/images/home.png",{class: "homeicon"} %>
<% end %>
<br>
<br>

<table>
  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><li><%= block.block %></li></td>
        <td><%= link_to '編集', edit_block_path(block) %></td>
        <td><%= link_to '削除', block, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
    </table>
    <%#= image_tag "/images/kirai.png",{class: "kirai"} %>
  </tbody>
</table>


<br>

<%= link_to 'ブロック追加', new_block_path %>

app/views/blocks/new.html.erb
<div class="blocktitle">
  <h1>ブロック追加</h1><br>
</div>

<%= render 'form', block: @block %>

<div class= "modoru">
  <%= link_to '戻る', blocks_path %>
</div>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ブロック:</strong>
  <%= @block.block %>
</p>

<div class= "modoru">
  <%= link_to '編集', edit_block_path(@block) %> |
  <%= link_to '戻る', blocks_path %>
</div>