config/routes.rb
Rails.application.routes.draw do
  get 'recipes/display'
  get 'recipes/details'
  get 'displays/display'
  #get 'recipes/search'
  resources :categories
  resources :favorites
  resources :shoppings
  resources :blocks
  get 'home/top'
  root to:'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/profile', to: 'users#show'
  delete '/unsubscribe', to: 'users#destroy'
  
  #get '/users/:id', to: 'users#show', as: 'profile'
  #delete '/users/:id', to: 'users#destroy', as: 'unsubscribe'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/recipes_search', to: 'recipes#search'
  post '/recipes_search', to: 'recipes#search'

  post 'addfood', to: 'shoppings#addfood'
end

app/models/shopping.rb
class Shopping < ApplicationRecord  
    belongs_to :user, optional: true
    belongs_to :recipe, optional: true
    validates :buy, presence: true
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
  before_action :set_shopping, only: %i[ show edit update destroy ]

  # GET /shoppings or /shoppings.json
  def index
    @shoppings = Shopping.all
  end

  # GET /shoppings/1 or /shoppings/1.json
  def show
  end

  # GET /shoppings/new
  def new
    @shopping = Shopping.new
  end

  # GET /shoppings/1/edit
  def edit
  end

  # POST /shoppings or /shoppings.json
  def create
    @shopping = Shopping.new(shopping_params)
    @shopping.user_id = current_user.id

    respond_to do |format|
      if @shopping.save
        format.html { redirect_to shopping_url(@shopping), notice: "Shopping was successfully created." }
        format.json { render :show, status: :created, location: @shopping }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shopping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoppings/1 or /shoppings/1.json
  def update
    respond_to do |format|
      if @shopping.update(shopping_params)
        format.html { redirect_to shopping_url(@shopping), notice: "Shopping was successfully updated." }
        format.json { render :show, status: :ok, location: @shopping }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shopping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoppings/1 or /shoppings/1.json
  def destroy
    @shopping.destroy

    respond_to do |format|
      format.html { redirect_to shoppings_url, notice: "Shopping was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def addfood
    shopping = Shopping.new
    shopping.user_id = current_user.id
    shopping.buy = params[:buy]
    shopping.memo = params[:memo]
    shopping.recipe_id = params[:recipe_id]
    if shopping.save
      redirect_to recipes_details_path(id: params[:recipe_id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping
      @shopping = Shopping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shopping_params
      params.require(:shopping).permit(:buy, :memo, :user_id, :favorite, :recipe_id)
    end
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/shoppings/_form.html.erb
<%= form_with(model: shopping) do |form| %>
  <% if shopping.errors.any? %>
    <div id="error_explanation">
      <ul class = "era">
        <% shopping.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :buy %>
    <%= form.text_field :buy %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo %>
  </div>
  
  <%#div class="field">
    <%= form.label :user_id %>
    <%#= form.number_field :user_id %>
  <%#/div%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoppings/edit.html.erb
<h1>編集</h1>

<%= render 'form', shopping: @shopping %>

<%= link_to '詳細', @shopping %> |
<%= link_to '戻る', shoppings_path %>

app/views/shoppings/index.html.erb
<div class="blocktitle">
  <h1>買い物リスト</h1>

</div>

<%#ホームアイコン%>
<%= link_to home_top_path do %>
  <%= image_tag "/images/home.png",{class: "homeicon"} %>
<% end %>
<br>
<br>

<table>
  <tbody>
    <% @shoppings.each do |shopping| %>
      <tr>

        
        <td><li><%= shopping.buy %></li></td>
        <td><%#= shopping.recipe.recipeTitle%></td>
        <td><%= link_to '詳細', shopping %></td>
        <td><%= link_to '編集', edit_shopping_path(shopping) %></td>
        <td><%= link_to '削除', shopping, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '追加', new_shopping_path %>

app/views/shoppings/new.html.erb
<div class="blocktitle">
<h1>購入品追加</h1>
<br>
<br>
</div>

<%= render 'form', shopping: @shopping %>

<%= link_to '戻る', shoppings_path %>

app/views/shoppings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>購入品:</strong>
  <%= @shopping.buy %>
</p>

<p>
  <strong>メモ:</strong>
  <%= @shopping.memo %>
</p>

<% unless @shopping.recipe_id.nil? %>
  <p>
    <strong>レシピ:</strong>
    <%= link_to @shopping.recipe.recipeTitle,recipes_details_path(id: @shopping.recipe_id)%>
  </p>
<% end %>

<%= link_to '編集', edit_shopping_path(@shopping) %> |
<%= link_to '戻る', shoppings_path %>